version: "3"
services:
  openapi-ui:
    image: swaggerapi/swagger-ui
    container_name: "blog-openapi-ui"
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yml
    volumes:
      - ./openapi:/openapi
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "blog-server"
    volumes:
      - ./credentials.json:$PWD/credentials.json
    environment:
      AUTH_SECRET: yt8492blog
      BLOG_DOMAIN: blog.yt8492.com
      GOOGLE_APPLICATION_CREDENTIALS: $PWD/credentials.json
    ports:
      - "8080:8080"
