version: "3"
services:
  openapi-ui:
    image: swaggerapi/swagger-ui
    container_name: "blog-openapi-ui"
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yml
    volumes:
      - ./openapi:/openapi