version: "3"
services:
  openapi-ui:
    image: swaggerapi/swagger-ui
    container_name: "blog-openapi-ui"
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yml
    volumes:
      - ./openapi:/openapi
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "blog-server"
    environment:
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      DB_URL: jdbc:mysql://db:3306/blog-db
      DB_USER: yt8492
      DB_PASSWORD: password
      AUTH_SECRET: yt8492blog
      BLOG_DOMAIN: blog.yt8492.com
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0.22
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: yt8492
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: blog-db
    ports:
      - "3306:3306"
